name: politic
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fixnum: ^0.10.5
  protobuf: ^0.10.2
  logging: ^0.11.3+2
  flutter_localizations:
    sdk: flutter
  path_provider: ^1.3.0
  collection: ^1.14.11
  tuple: ^1.0.2
  flutter_local_notifications: ^0.8.2
  firebase_analytics: ^5.0.1
  firebase_messaging: ^5.1.5
  firebase_performance: ^0.3.0+5
  firebase_crashlytics: ^0.1.0+3
#   firebase_admob: ^0.9.0+7
  intl_translation: ^0.17.7
  http: ^0.12.0+1
  json_annotation: ^3.0.0
  flutter_simple_dependency_injection: any
  package_info: ^0.4.0+6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^4.3.1
  flutter_markdown: ^0.4.2
  url_launcher: ^5.5.0
  flutter_google_places: ^0.2.5
  location: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

flutter:
  assets:
    - res/images/enrolled.png
    - res/images/notenrolled.png
    - res/images/notifications.png
    - res/images/location_services.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true